
- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - all

- hosts: wmaster
  serial: 1
  remote_user: vagrant
  become: yes
  roles:
    - all
    - consul
    - monitor
    - efk
    - swarm
  vars:
    - consul_master: true
    - swarm_master: true

- hosts: wnodes
  serial: 1
  remote_user: vagrant
  become: yes
  roles:
    - all
    - consul
    - monitor-node
    - swarm