
# not used

- hosts: consul-master, consul-agents
  serial: 1
  remote_user: vagrant
  become: yes
  roles:
    - all
    - {
        role: consul,
        is_consul_master: "{{ 'consul-master' in group_names }}",
        is_consul_agent: "{{ 'consul-agents' in group_names }}",
        tags: ['consul']
      }
