
- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - all

- hosts: wmaster
  serial: 1
  remote_user: vagrant
  become: yes
  roles:
#    - monitor
#    - efk
    - swarmkit
  vars:
    - swarm_master: true

- hosts: wnodes
  serial: 1
  remote_user: vagrant
  become: yes
  roles:
#    - monitor-node
    - swarmkit
