- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    #repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    update_cache: yes
    state: present
  register: result
  until: result|success
  retries: 10
  tags: [docker]

- name: Install Docker engine
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Install python-pip
  apt: name=python-pip state=present
  tags: [docker]

- name: Install docker-py
  pip:
    name: docker-py
    version: 1.9.0
    state: present
  tags: [docker]

- name: Add vagrant user to the docker group
  user:
    name: vagrant
    group: docker
  notify:
    - Restart Docker
  tags: [docker]
