- include: "{{ a_lib_tasks }}/dirs.yml"
  vars:
    dirs: "{{ master_directories }}"
  when: swarm_master is defined
  tags: [swarm]

- include: "{{ a_lib_tasks }}/files.yml"
  vars:
    files: "{{ master_scripts }}"
  when: swarm_master is defined
  tags: [swarm]

- name: Remove obsolete Docker init.d service
  file:
    dest: /etc/init.d/docker
    state: absent
  tags: [swarm]

- name: Update Docker configuration
  copy:
    src: docker.cfg
    dest: /etc/default/docker
  notify:
    - Restart Docker
  when: not swarm_master is defined
  tags: [swarm]

- name: Run Swarm master
  docker:
    name: swarm-master
    image: swarm
    ports: 4000:4000
    expose:
      - 4000
    command: manage -H :4000 -advertise {{ ip }}:4000 consul://{{ ip }}:8500/myswarm
    env:
      SERVICE_ID: swarm-master
  when: swarm_master is defined
  tags: [swarm]

- name: Run Swarm node
  docker:
    name: swarm-node
    image: swarm
    command: join --advertise={{ ip }}:4000 consul://{{ ip }}:8500/myswarm
  when: not swarm_master is defined
  tags: [swarm]
