- include: "{{ a_lib_tasks }}/dirs.yml"
  vars:
    dirs: "{{ master_directories }}"
  when: swarm_master is defined
  tags: [swarm]

- include: "{{ a_lib_tasks }}/files.yml"
  vars:
    files: "{{ master_scripts }}"
  when: swarm_master is defined
  tags: [swarm]

- include: "{{ a_lib_tasks }}/templates.yml"
  tags: [swarm]

- name: Remove obsolete Docker init.d service
  file:
    dest: /etc/init.d/docker
    state: absent
  tags: [swarm]

- name: Update Docker configuration
  copy:
    src: /docker.cfg
    dest: /etc/default/docker
  notify:
    - Restart Docker
  when: not swarm_master is defined
  tags: [swarm]

- name: Run Swarm master
  docker_service:
    project_name: swarm-master
    definition:
      version: '2'
      services:
        swarm-master:
          image: swarm
          command: manage -H :4000 --advertise {{ ip }}:4000 consul://{{ ip }}:8500/myswarm
          restart: unless-stopped
          ports:
            - 4000:4000
          expose:
            - 4000
          volumes:
            - /etc/docker/tls:/etc/docker/tls
  when: swarm_master is defined
  tags: [swarm]

- name: Run Swarm node
  docker_service:
    project_name: swarm-node
    definition:
      version: '2'
      services:
        swarm-node:
          image: swarm
          command: join --advertise={{ ip }}:2375 consul://{{ consul_master_ip }}:8500/myswarm
  when: not swarm_master is defined
  tags: [swarm]
