
- name: Remove obsolete Docker init.d service
  file:
    dest: /etc/init.d/docker
    state: absent

- include: swarm-master.yml
  when: swarm_master is defined

- include: swarm-nodes.yml
  when: swarm_master is undefined
