
- name: Remove obsolete Docker init.d service
  file:
    dest: /etc/init.d/docker
    state: absent

- include: swarm-master.yml
  when: is_swarm_master

- include: swarm-nodes.yml
  when: is_swarm_node
