
- include: "{{ a_lib_tasks }}/dirs.yml"
  vars:
    dirs: "{{ master_directories }}"

- include: "{{ a_lib_tasks }}/files.yml"
  vars:
    files: "{{ master_scripts }}"

- include: "{{ a_lib_tasks }}/templates.yml"

- name: Run Swarm master
  docker_service:
    project_name: swarm-master
    definition:
      version: '2'
      services:
        swarm-master:
          image: swarm
          command: manage -H :4000 --advertise {{ ip }}:4000 consul://{{ ip }}:8500/myswarm
          restart: unless-stopped
          ports:
            - 4000:4000
          expose:
            - 4000
          volumes:
            - /etc/docker/tls:/etc/docker/tls
