
- include: "{{ a_lib_tasks }}/templates.yml"

- name: Update Docker configuration
  copy:
    src: /docker.cfg
    dest: /etc/default/docker
  notify:
    - Restart Docker

- name: Run Swarm node
  docker_service:
    project_name: swarm-node
    definition:
      version: '2'
      services:
        swarm-node:
          image: swarm
          command: join --advertise={{ ip }}:2375 consul://{{ consul_master_ip }}:8500/myswarm
