
- name: Remove obsolete Docker init.d service
  file:
    dest: /etc/init.d/docker
    state: absent

- name: Install SwarmKit
  shell: "go get -d github.com/docker/swarmkit && cd {{ gopath }}/src/github.com/docker/swarmkit && make binaries"
  environment:
    GOPATH: "{{ gopath }}"

- include: swarmkit-master.yml
  when: swarm_master is defined
  environment:
    PATH: "{{ swarmkit_path }}:{{ lookup('env', 'PATH') }}"

- include: swarmkit-nodes.yml
  when: swarm_master is undefined
  environment:
    PATH: "{{ swarmkit_path }}:{{ lookup('env', 'PATH') }}"
