---

- name: Init "Swarm Mode" on the first manager
  shell: docker swarm init
        --listen-addr {{ ip }}:{{ docker_swarm_port }}
        --advertise-addr {{ ip }}
  when: "docker_info.stdout.find('Swarm: active') == -1"

- name: Get the worker join-token
  shell: docker swarm join-token -q worker
  changed_when: False
  run_once: true
  register: docker_worker_token

- name: Get the manager join-token
  shell: docker swarm join-token -q manager
  changed_when: False
  run_once: true
  register: docker_manager_token

- name: Export the address of the first Swarm manager as a fact
  set_fact:
    docker_manager_address: "{{ ip }}:{{ docker_swarm_port }}"
  run_once: true

#- name: Join the pending Swarm manager nodes.
#  shell: docker swarm join
#        --listen-addr {{ docker_swarm_addr }}:{{ docker_swarm_port }}
#        --advertise-addr {{ docker_swarm_addr }}
#        --token "{{ docker_manager_token.stdout }}"
#        {{ docker_manager_address }}
#  changed_when: False
#  when: "docker_info.stdout.find('Swarm: active') == -1
#    and docker_info.stdout.find('Swarm: pending') == -1
#    and 'docker_swarm_manager' in group_names"