
- set_fact:
    docker_worker_token: "{{ hostvars[smarm_master].docker_worker_token.stdout }}"

- name: Join the pending Swarm worker nodes.
  shell: docker swarm join
        --listen-addr {{ ip }}:{{ docker_swarm_port }}
        --advertise-addr {{ ip }}
        --token "{{ docker_worker_token }}"
        {{ smarm_master }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1"
